# EFTCosmoMC settings: just a simple EFTCAMB model to start

EFTflag          = 0
PureEFTmodel     = 1
PureEFTHorndeski = F

EFTwDE             = 0
PureEFTmodelOmega  = 3
PureEFTmodelGamma1 = 0
PureEFTmodelGamma2 = 0
PureEFTmodelGamma3 = 0
PureEFTmodelGamma4 = 0
PureEFTmodelGamma5 = 0
PureEFTmodelGamma6 = 0

EFT_mathematical_stability = F
; EFT_physical_stability     = T
EFT_ghost_stability      = F
EFT_gradient_stability   = F
EFT_additional_priors      = F

param[EFTOmega0]   = 0.01 -1 1 0.1 0.1
param[EFTOmegaExp] = 1.00  0 5 0.1 0.1

root_dir = chains/
file_root = test_eft_2

# to test a chain:
; feedback  = 1
; action    = 0
; samples   = 100000000
; logzero_trace = T
# to test one sample:
feedback = 4
action = 4
samples = 1
EFTCAMB_feedback_level = 3
; test_check_compare =  1821.540    

num_threads = 0
stop_on_error = F
checkpoint = F
propose_matrix =  
estimate_propose_matrix = F

use_clik = F
use_HST  = F
use_mpk  = F
use_SN   = F
use_BAO  = T
use_Age_Tophat_Prior = F
nonlinear_pk = F

indep_sample = 10

INCLUDE(batch3/params_CMB_defaults.ini)
DEFAULT(batch3/BAO.ini)
