# EFTCosmoMC settings: just a simple EFTCAMB model to start

EFTflag          = 4
; PureEFTmodel     = 1
; PureEFTHorndeski = F

; EFTwDE             = 0
; PureEFTmodelOmega  = 3
; PureEFTmodelGamma1 = 0
; PureEFTmodelGamma2 = 0
; PureEFTmodelGamma3 = 0
; PureEFTmodelGamma4 = 0
; PureEFTmodelGamma5 = 0
; PureEFTmodelGamma6 = 0

FullMappingEFTmodel = 5

Omega_model  = 3    
Lambda_model = 3

Omega_Pade_order_N = 5
Omega_Pade_order_D = 4

Omegaa0 = 1
param[OmegaN0] = 0 -1 1 0.0001 0.1
param[OmegaN1] = 0 -1 1 0.0001 0.1
param[OmegaN2] = 0 -1 1 0.0001 0.1
param[OmegaN3] = 0 -1 1 0.0001 0.1
param[OmegaN4] = 0 -1 1 0.0001 0.1
param[OmegaN5] = 0 -1 1 0.0001 0.1
param[OmegaD1] = 0 -1 1 0.0001 0.1
param[OmegaD2] = 0 -1 1 0.0001 0.1
param[OmegaD3] = 0 -1 1 0.0001 0.1
param[OmegaD4] = 0 -1 1 0.0001 0.1

Lambda_Pade_order_N = 5
Lambda_Pade_order_D = 4

Lambdaa0 = 1
param[LambdaN0] = 0 -1 1 0.0001 0.1
param[LambdaN1] = 0 -1 1 0.0001 0.1
param[LambdaN2] = 0 -1 1 0.0001 0.1
param[LambdaN3] = 0 -1 1 0.0001 0.1
param[LambdaN4] = 0 -1 1 0.0001 0.1
param[LambdaN5] = 0 -1 1 0.0001 0.1
param[LambdaD1] = 0 -1 1 0.0001 0.1
param[LambdaD2] = 0 -1 1 0.0001 0.1
param[LambdaD3] = 0 -1 1 0.0001 0.1
param[LambdaD4] = 0 -1 1 0.0001 0.1

; param[Omega0] = 0 -1 1 0.1 0.1
; param[Omega1] = 0 -1 1 0.1 0.1
; param[Omega2] = 0 -1 1 0.1 0.1
; param[Omega3] = 0 -1 1 0.1 0.1
; param[Omega4] = 0 -1 1 0.1 0.1
; param[Omega5] = 0 -1 1 0.1 0.1
; param[Omega6] = 0 -1 1 0.1 0.1
; param[Omega7] = 0 -1 1 0.1 0.1

; param[Lambda0] = 0 -1 1 0.1 0.1
; param[Lambda1] = 0 -1 1 0.1 0.1
; param[Lambda2] = 0 -1 1 0.1 0.1
; param[Lambda3] = 0 -1 1 0.1 0.1
; param[Lambda4] = 0 -1 1 0.1 0.1
; param[Lambda5] = 0 -1 1 0.1 0.1
; param[Lambda6] = 0 -1 1 0.1 0.1
; param[Lambda7] = 0 -1 1 0.1 0.1

EFT_mathematical_stability = F
EFT_physical_stability     = T
EFT_additional_priors      = T

; param[EFTOmega0]   = 0.01 -q

root_dir = chains/
file_root = eft_horndeski

# to test a chain:
; feedback  = 1
; action    = 0
; samples   = 10000000
# to test one sample:
feedback = 4
action = 4
samples = 1
; test_check_compare =  1821.540    

num_threads = 0
stop_on_error = T
checkpoint = F
propose_matrix =  
estimate_propose_matrix = F

use_clik = F
use_HST  = F
use_mpk  = F
use_SN   = F
use_BAO  = T
use_Age_Tophat_Prior = F
nonlinear_pk = F

indep_sample = 10

INCLUDE(batch3/params_CMB_defaults.ini)
DEFAULT(batch3/BAO.ini)

# include the standard CosmoMC test file:
; DEFAULT(test.ini)
; DEFAULT(test_SN.ini)
; DEFAULT(test_planck.ini)
